name: Post Prevision New Account Custom Steps
description: "Custom logic to run after account provisioning"
inputs:
  PIPELINES_READ_TOKEN:
    description: "The PIPELINES_READ_TOKEN secret"
    required: true
  INFRA_ROOT_WRITE_TOKEN:
    description: "The INFRA_ROOT_WRITE_TOKEN secret"
    required: true
  gruntwork_context:
    description: "Gruntwork Context From the Gruntwork Bootstrap step"
    required: true
runs:
  using: composite
  steps:
    - name: Custom Logic Goes Here
      shell: bash
      run: |
        echo 'hello world'
