name: Pipelines Execute
run-name: Run Gruntwork Pipelines
on:
  workflow_call:
    secrets:
      GRUNTWORK_CODE_ACCESS_TOKEN:
        required: true

env:
  DEPLOY_BRANCH_NAME: main
  GRUNTWORK_INSTALLER_VERSION: v0.0.39
  MODULE_SECURITY_VERSION: v0.68.3
  CONTROL_TOWER_MODULES_VERSION: v0.4.2
  BOILERPLATE_VERSION: v0.5.8

jobs:
  preflight_checks:
    name: Run config preflight checks for gruntwork pipelines
    runs-on: ubuntu-latest
    env:
      GRUNTWORK_CODE_ACCESS_TOKEN: ${{ secrets.GRUNTWORK_CODE_ACCESS_TOKEN }}
    steps:
      - name: Update comment
        uses: gruntwork-io/pipelines-status-update@v0.1.0
        with:
          step_name: "Preflight Checks"
          step_status: "in_progress"
          first_update: true

      - name: Ensure CI User Variables are populated
        shell: bash
        run: |
          if [[ -z "$GRUNTWORK_CODE_ACCESS_TOKEN" ]]; then echo "Missing GRUNTWORK_CODE_ACCESS_TOKEN"; exit 1; fi
      # See https://stackoverflow.com/a/76151412
      - uses: actions/checkout@v4
        # Only run if this is a pull request and the target branch is main
        if: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main' }}
        with:
          fetch-depth: 0
      - name: Check if branch is ahead of main
        # Only run if this is a pull request and the target branch is main
        if: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main' }}
        env:
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        run: |
          if ! git merge-base --is-ancestor origin/main "$HEAD_SHA"; then
            echo "::error::Branch is not up to date with main"
            exit 1
          fi
      - name: Update comment
        uses: gruntwork-io/pipelines-status-update@v0.1.0
        with:
          step_name: "Preflight Checks"
          step_status: "success"
          step_details: "Validated envvars and git branch status"

  detect_changes:
    name: Detect Infrastructure Changes
    runs-on: ubuntu-latest
    needs: [preflight_checks]
    steps:
      - name: Update comment
        uses: gruntwork-io/pipelines-status-update@v0.1.0
        with:
          step_name: "Calculate Infrastructure Changes"
          step_status: "in_progress"

      - uses: actions/checkout@v4
        with:
          # Fetch all history
          fetch-depth: 0

      - name: Read Gruntwork config file
        id: gruntwork
        shell: bash
        run: |
          config="$(cat .gruntwork/config.yml | base64 -w 0)"
          echo "config=$config" >> $GITHUB_OUTPUT
          pipelines_cli_version="$(yq -r .pipelines.cli-version .gruntwork/config.yml)"
          echo "pipelines_cli_version=$pipelines_cli_version" >> $GITHUB_OUTPUT

      - name: Set custom ref variables
        id: ref
        # If this run was triggered manually, we'll use the source and target ref from the user input. Otherwise, we'll
        # use our default approach.
        # pull requests need to use pull_request.head.sha, rather than HEAD, because by default HEAD for PRs is a merge commit that isn't in the actual history
        run: |
          echo "source_ref=${{ inputs.source_ref || '$(./.github/scripts/source-ref.sh)'}}" >> $GITHUB_OUTPUT

          if [[ '${{  github.event_name }}' = 'pull_request' ]]; then
            echo "branch_ref=${{ inputs.target_ref || github.event.pull_request.head.sha }}" >> $GITHUB_OUTPUT
          else
            echo "branch_ref=${{ inputs.target_ref || '$(git rev-parse HEAD)'}}" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Get event-type
        id: event_type
        run: |
          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
              echo "event_type=push" >> $GITHUB_OUTPUT
          else
              echo "event_type=pr-synched-created" >> $GITHUB_OUTPUT
          fi

      - name: Pipelines Orchestrate
        id: orchestrate
        uses: gruntwork-io/pipelines-orchestrate@v1.1.0
        with:
          repository-path: "."
          repository-url: ${{ github.server_url }}/${{ github.repository }}
          source-ref: ${{ steps.ref.outputs.source_ref }}
          target-ref: ${{ steps.ref.outputs.branch_ref }}
          event-type: ${{ steps.event_type.outputs.event_type }}
          gruntwork-config: ${{ steps.gruntwork.outputs.config }}
          # We do this because the `GRUNTWORK_CODE_ACCESS_TOKEN` might not be present when vending a delegated account, even though it's always present in the main `infrastructure-live` account.
          token: ${{ secrets.GRUNTWORK_CODE_ACCESS_TOKEN || secrets.GITHUB_TOKEN }}

      - name: Update comment
        uses: gruntwork-io/pipelines-status-update@v0.1.0
        with:
          step_name: "Calculate Infrastructure Changes"
          step_status: "success"
          step_details: ${{ steps.orchestrate.outputs.jobs }}

    outputs:
      pipelines_jobs: ${{ steps.orchestrate.outputs.jobs }}
      pipelines_cli_version: ${{ steps.gruntwork.outputs.pipelines_cli_version }}

  pipelines_determine:
    name: ${{ matrix.jobs.ChangeType }} - ${{ matrix.jobs.WorkingDirectory }}
    needs: [detect_changes]
    runs-on: ubuntu-latest
    # GHA can't check for length, so we just check if there is an item in the 0 index
    if: fromJson(needs.detect_changes.outputs.pipelines_jobs)[0] != null
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        jobs: ${{ fromJson(needs.detect_changes.outputs.pipelines_jobs) }}
    steps:
      - name: Check out repo code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Update comment
        uses: gruntwork-io/pipelines-status-update@v0.1.0
        with:
          step_name: ${{ matrix.jobs.ChangeType }} - ${{ matrix.jobs.WorkingDirectory }}
          step_status: "in_progress"

      - name: Bootstrap Workflow
        id: bootstrap
        uses: gruntwork-io-team/pipelines-bootstrap@main
        with:
          token: ${{ secrets.GRUNTWORK_CODE_ACCESS_TOKEN }}
          change_type: ${{ matrix.jobs.ChangeType }}
          branch: ${{ matrix.jobs.Ref }}
          working_directory: ${{ matrix.jobs.WorkingDirectory }}
          account_id: ${{ matrix.jobs.AccountId }}
          terragrunt_command: ${{ matrix.jobs.Action.Command }} ${{ matrix.jobs.Action.Args }}
          additional_data: ${{ toJson(matrix.jobs.AdditionalData) }}
          child_account_id: ${{ matrix.jobs.AdditionalData.ChildAccountId }}
          new_account_name: ${{ matrix.jobs.AdditionalData.AccountName }}
          team_account_names: ${{ matrix.jobs.AdditionalData.TeamAccountNames }}

      - name: "[Baseline]: Apply New Account Baseline"
        if: steps.bootstrap.outputs.workflow == 'apply-new-account-baseline.yml'
        uses: gruntwork-io-team/pipelines-baseline-account-action@main
        with:
          gruntwork_code_access_token: ${{ secrets.GRUNTWORK_CODE_ACCESS_TOKEN }}
          terragrunt_command: ${{ steps.bootstrap.outputs.terragrunt_command }}
          new_account_name: ${{ steps.bootstrap.outputs.new_account_name }}

      - name: "[ProvisionAccount]: Setup access-control PR"
        id: provision_access_control
        if:  ${{ steps.bootstrap.outputs.workflow == 'create-account-and-generate-baselines.yml' }}
        uses: gruntwork-io-team/pipelines-provision-account-action@main
        with:
          new_account_name: ${{ steps.bootstrap.outputs.new_account_name }}
          terragrunt_command: ${{ steps.bootstrap.outputs.terragrunt_command }}
          branch: ${{ steps.bootstrap.outputs.branch }}
          gruntwork_code_access_token: ${{ secrets.GRUNTWORK_CODE_ACCESS_TOKEN }}

      - name: "[ProvisionDelegatedRepo]: Setup delegated Repo"
        id: provision_delegated_repo
        if:  ${{ steps.bootstrap.outputs.workflow == 'provision-delegated-account.yml' }}
        uses: gruntwork-io-team/pipelines-provision-repo-action@main
        with:
          new_account_name: ${{ steps.bootstrap.outputs.new_account_name }}
          terragrunt_command: ${{ steps.bootstrap.outputs.terragrunt_command }}
          gruntwork_code_access_token: ${{ secrets.GRUNTWORK_CODE_ACCESS_TOKEN }}
          # TODO - this needs to be a different token that has enhanced scopes for creating repos
          manage_repo_token: ${{ secrets.GRUNTWORK_CODE_ACCESS_TOKEN }}

      - name: "[TerragruntExecute]: Authenticate with AWS and then Invoke Terragrunt"
        id: terragrunt
        if:  ${{ steps.bootstrap.outputs.workflow == 'terragrunt-execute.yml' }}
        uses: gruntwork-io-team/pipelines-aws-execute@main
        with:
          gruntwork_code_access_token: ${{ secrets.GRUNTWORK_CODE_ACCESS_TOKEN }}
          terragrunt_command: ${{ steps.bootstrap.outputs.terragrunt_command }}
          account_id: ${{ steps.bootstrap.outputs.account_id }}
          aws_region: ${{ steps.bootstrap.outputs.aws_region }}
          branch: ${{ steps.bootstrap.outputs.branch }}
          working_directory: ${{ steps.bootstrap.outputs.working_directory }}
          account_role_name: ${{ steps.bootstrap.outputs.role_name }}
          role_session_name: ${{ steps.bootstrap.outputs.role_session_name }}
          chain_account_id: ${{ steps.bootstrap.outputs.child_account_id }}
          chain_account_role_name: ${{ steps.bootstrap.outputs.child_acct_role_name }}


    outputs:
      account_id: ${{ matrix.jobs.AccountId }}
      branch: ${{ steps.bootstrap.outputs.branch }}
      workflow: ${{ steps.bootstrap.outputs.workflow }}
      working_directory: ${{ steps.bootstrap.outputs.working_directory }}
      terragrunt_command: ${{ steps.bootstrap.outputs.terragrunt_command }}
      additional_data: ${{ steps.bootstrap.outputs.additional_data }}
      child_account_id: ${{ steps.bootstrap.outputs.child_account_id }}
      new_account_name: ${{ steps.bootstrap.outputs.new_account_name }}
      team_account_names: ${{ steps.bootstrap.outputs.team_account_names }}
